### PR TITLE
#50: RSS parse for landing pages

### LINKED ISSUE #50: Fetch and parse episode and series data

### PR DESCRIPTION
**Pull request by rpeterman-gp**
Closes #50 

- Adds RSS data parsers for series and listen pages
- Updates series and listen pages

## To Review

- [x] Checkout Branch.
- [x] Run `nvm use`.
- [x] Run `yarn`.
- [x] Run `yarn dev`.

> ...then...

- [x] Go to http://localhost:3000/series?uf=http://feed.songexploder.net/SongExploder
- [x] Ensure expected info is shown in header and in episode items. (Ignore content layout and formatting. Other tickets will address those.)
- [x] Go to http://localhost:3000/listen?uf=http://feed.songexploder.net/SongExploder&ge=prx_93_c69f47ef-fffd-4b88-b52e-0b2c18c9b998
- [x] Ensure expected info is shown in header and in episode content. (Ignore content layout and formatting. Other tickets will address those.)
- [x] Run `yarn test --coverage`
- [x] Ensure test pass with 💯 .

### CODE REVIEW

**Review by brandonhundt — CHANGES_REQUESTED** [review]
1. I noticed that December dates are rendering as 00/DD instead of 12/DD

localhost_3000_series_uf=http___feed songexploder net_SongExploder

**Comment by brandonhundt** [comment]
2. When I visit http://localhost:3000/listen?uf=http://feed.songexploder.net/SongExploder&ge=prx_93_c69f47ef-fffd-4b88-b52e-0b2c18c9b998 I get the following error:

```
error - components/Player/Player.tsx (56:5) @ Player
ReferenceError: currentTrackDurationSeconds is not defined
  54 |         audioElm.current.duration || currentTrackDurationSeconds
  55 |       ),
> 56 |     [currentTrackDurationSeconds]
     |     ^
  57 |   );
  58 | 
  59 |   const boundedVolume = useCallback(
```

Screen Shot 2022-07-05 at 12 33 38 PM

**Comment by brandonhundt** [comment]
3. A few things in the header. Missing the show logo + the HTML is being rendered on the page. I understand if these items are part of the formatting to come. 
 
localhost_3000_series_uf=http___feed songexploder net_SongExploder (1)

4. I don't know if this feedback is for this ticket, but the PRX logo in the header is really small. In Augury the PRX logo is rendered at 113px x 73px, this should be similar. Thanks.

**Comment by rpeterman-gp** [comment]
> 1. I noticed that December dates are rendering as 00/DD instead of 12/DD
> 
> localhost_3000_series_uf=http___feed songexploder net_SongExploder

That would be January. This implementation is just a quick placeholder version. Accurate rendering of date values will come in page content tickets.

**Comment by rpeterman-gp** [comment]
> 3. A few things in the header. Missing the show logo + the HTML is being rendered on the page. I understand if these items are part of the formatting to come.
> 
> localhost_3000_series_uf=http___feed songexploder net_SongExploder (1)
> 
> 4. I don't know if this feedback is for this ticket, but the PRX logo in the header is really small. In Augury the PRX logo is rendered at 113px x 73px, this should be similar. Thanks.

3. Rendering of HTML content values will come in a later ticket.
4. We are basing our styling on the Figma designs, which have the logo at 95px. I'll update the logo width to 113px.

**Comment by rpeterman-gp** [comment]
> 2. When I visit http://localhost:3000/listen?uf=http://feed.songexploder.net/SongExploder&ge=prx_93_c69f47ef-fffd-4b88-b52e-0b2c18c9b998 I get the following error:
> 
> ```
> error - components/Player/Player.tsx (56:5) @ Player
> ReferenceError: currentTrackDurationSeconds is not defined
>   54 |         audioElm.current.duration || currentTrackDurationSeconds
>   55 |       ),
> > 56 |     [currentTrackDurationSeconds]
>      |     ^
>   57 |   );
>   58 | 
>   59 |   const boundedVolume = useCallback(
> ```
> 
> Screen Shot 2022-07-05 at 12 33 38 PM

Looks like a merge error. Just pushed up a fix.

**Review by brandonhundt — APPROVED** [review]
Alright the data is there :shipit:

**Pull request merged**
